### ISSUE TITLE
Limerick Corpus

### ISSUE THREAD

**Issue by tnhaider** [harsh19/Structured-Adversary#2]
Could you share your crawled version of the Limerick corpus?

I am currently collecting poetry resources for a larger NLP publication.

Unfortunately, http://hardsoft.us/limindex.htm looks rather messy, so I would appreciate it if you could upload your version that can be processed. We would of course cite your paper then.

Thanks in advance!

**Comment by harsh19** [comment]
Hi,
Will this work: https://drive.google.com/drive/u/1/folders/1CZX_Iu4rTpzT6vdzIO_kWw-79lhFR0_u ?
